DROP TABLE CARACTERISTICAS;
DROP TABLE CATEGORIAS;
DROP TABLE CONTACTOS;
DROP TABLE INFOPEDIDOS;
DROP TABLE PEDIDOS;
DROP TABLE PRODUCTOS;
DROP TABLE SESIONES;
DROP TABLE TRABAJOS;
DROP TABLE USUARIOS;
DROP TABLE LOCALES;



ALTER TABLE INFOPEDIDOS ADD CONSTRAINT FK_ID_PRODUCTOS
FOREIGN KEY ID_PRODUCTOS
REFERENCES PRODUCTOS(ID_PRODUCTOS);
ALTER TABLE INFOPEDIDOS ADD CONSTRAINT FK_N_PEDIDOS
FOREIGN KEY N_PEDIDOS
REFERENCES PEDIDOS(N_PEDIDOS);
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_ID_USUARIO
FOREIGN KEY ID_USUARIO
REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_ID_CATEGORIA
FOREIGN KEY ID_CATEGORIA
REFERENCES CATEGORIAS(ID_CATEGORIA);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_ID_CARACTERISTICAS
FOREIGN KEY ID_CARACTERISTICAS
REFERENCES CARACTERISTICAS(ID_CARACTERISTICAS);
ALTER TABLE SESIONES ADD CONSTRAINT FK_ID_USUARIO
FOREIGN KEY ID_USUARIO
REFERENCES USUARIOS(ID_USUARIO);
ALTER TABLE TRABAJOS ADD CONSTRAINT FK_ID_USUARIO
FOREIGN KEY ID_USUARIO
REFERENCES USUARIOS(ID_USUARIO);